name: Create GCP resource by terraform

on:
  workflow_dispatch:
      
permissions:
  id-token: write
  contents: read

jobs:
  create-resource:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.0
    

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/833145775514/locations/global/workloadIdentityPools/github-new/providers/github-new'
        service_account: 'github@mm-programming.iam.gserviceaccount.com'

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform
      run: terraform plan

    - name: Apply Terraform
      run: terraform apply -auto-approve
